# Generated by Django 4.2.21 on 2025-06-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=200)),
                ('founder_name', models.CharField(max_length=200)),
                ('startup_description', models.TextField()),
                ('intro_video', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('pitch_deck', models.FileField(blank=True, null=True, upload_to='pitch/')),
            ],
        ),
    ]
